version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www/html
      - ./docker/prod/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot/:ro
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  mysql:
    image: mariadb:lts
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      SERVICE_NAME: mysql
    networks:
      - laravel

  php:
    build:
      context: ./docker/prod/php
    container_name: php
    user: "${USER_ID}:${GROUP_ID}"
    volumes:
      - .:/var/www/html
      - ./data/certbot/conf:/etc/letsencrypt
    ports:
      - "9000:9000"
    networks:
      - laravel

  npm:
    image: node:latest
    container_name: npm
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot/:rw

networks:
  laravel:

volumes:
  mysql:
    driver: local
