name: Deploy

on:
  workflow_run:
    workflows:
      - Laravel
    types:
      -

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Deploy test
    runs-on: ubuntu-latest
    steps:
      - run: env
